#.travis.yml

sudo: required

dist: trusty

language: node_js

node_js:
  - 6

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - ng build --prod --base-href /

notifications:
  email:
    on_failure: change
    on_success: change
